# Generated by Django 5.0.7 on 2024-08-13 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_projectcontributormap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
